DROP DATABASE IF EXISTS LimitedGames;
CREATE DATABASE LimitedGames;
USE LimitedGames;

DROP TABLE IF EXISTS Gioco;
CREATE TABLE Gioco(
	ID INT AUTO_INCREMENT  PRIMARY KEY,
    Prezzo FLOAT NOT NULL,
    IVA FLOAT NOT NULL,
    Data_uscita DATE,
    Descrizione VARCHAR(300) NOT NULL,
    Titolo VARCHAR(40) NOT NULL,
    Immagine VARCHAR(400) NOT NULL,
    Edizione VARCHAR(40) NOT NULL,
    Sconto FLOAT
);

DROP TABLE IF EXISTS Piattaforma;
CREATE TABLE Piattaforma(
	Piattaforma VARCHAR(20) PRIMARY KEY
);

DROP TABLE IF EXISTS Stock;
CREATE TABLE Stock(
	IDGioco INT NOT NULL,
    Piattaforma VARCHAR(20) NOT NULL,
    Acquistati INT NOT NULL,
    Rimanenti INT NOT NULL,
	PRIMARY KEY(IDGioco,Piattaforma),
    FOREIGN KEY(IDGioco) REFERENCES Gioco(ID)
		ON UPDATE CASCADE ON DELETE CASCADE,
	FOREIGN KEY(Piattaforma) REFERENCES Piattaforma(Piattaforma)
		ON UPDATE CASCADE ON DELETE CASCADE
);

DROP TABLE IF EXISTS Utente;
CREATE TABLE Utente(
	Username VARCHAR(30) PRIMARY KEY,
    Pwd VARCHAR(500) NOT NULL,
    Nome VARCHAR(30) NOT NULL,
    Cognome VARCHAR(30) NOT NULL,
    Email VARCHAR(30) NOT NULL UNIQUE,
    Via VARCHAR(20) NOT NULL,
    CAP VARCHAR(5) NOT NULL,
    Citta VARCHAR(30) NOT NULL,
    Tipo VARCHAR(30) NOT NULL
);

DROP TABLE IF EXISTS Pagamento;
CREATE TABLE Pagamento(
	Numero VARCHAR(16) PRIMARY KEY,
    Nome VARCHAR(30) NOT NULL,
    Cognome VARCHAR(30) NOT NULL,
    Scadenza DATE NOT NULL,
    CVV VARCHAR(3) NOT NULL,
    Tipo VARCHAR(30) NOT NULL
);

DROP TABLE IF EXISTS Proprieta;
CREATE TABLE Proprieta(
	Utente VARCHAR(30) NOT NULL,
    Carta VARCHAR(16) NOT NULL,
    PRIMARY KEY(Utente,Carta),
    FOREIGN KEY(Utente) REFERENCES Utente(Username)
    ON UPDATE CASCADE ON DELETE CASCADE,
    FOREIGN KEY(Carta) REFERENCES Pagamento(Numero)
    ON UPDATE CASCADE ON DELETE CASCADE
);

DROP TABLE IF EXISTS Ordine;
CREATE TABLE Ordine(
	IDOrdine INT AUTO_INCREMENT PRIMARY KEY,
    Nome VARCHAR(30) NOT NULL,
    Cognome VARCHAR(30) NOT NULL,
    Via VARCHAR(20) NOT NULL,
    CAP VARCHAR(5) NOT NULL,
    Citta VARCHAR(30) NOT NULL,
    Prezzo float NOT NULL,
    Data_ordine DATE NOT NULL,
    Data_consegna DATE NOT NULL,
    Username VARCHAR(30) NOT NULL,
    FOREIGN KEY(Username) REFERENCES Utente(Username)
    ON UPDATE CASCADE ON DELETE NO ACTION
);

DROP TABLE IF EXISTS Acquisto;
CREATE TABLE Acquisto(
	IDAcquisto INT AUTO_INCREMENT PRIMARY KEY,
    IDOrdine INT NOT NULL,
    IDGioco INT NOT NULL,
    Quantita INT NOT NULL,
    DataAcquisto DATE NOT NULL,
    Titolo VARCHAR(40) not null,
    Prezzo float NOT NULL,
    IVA float NOT NULL,
    Edizione VARCHAR(40) NOT NULL,
    Piattaforma VARCHAR(20) NOT NULL,
    FOREIGN KEY(IDOrdine) REFERENCES Ordine(IDOrdine)
    ON UPDATE CASCADE ON DELETE CASCADE,
    FOREIGN KEY(IDGioco) REFERENCES Gioco(ID)
    ON UPDATE CASCADE ON DELETE NO ACTION
);
	
	
    
	
    




	
	
    
	
    
